function new-markdown{
    param([string]$name, [string]$title)

    Out-File -FilePath "$name.md" -InputObject "# $title"
}

function new-folder {
    param([string]$name, [string]$title)

    mkdir -Path $name
    Out-File -FilePath "$name/README.md" -InputObject "# $title"
}

#\s(?<=-name ".*)(?=.* -title)
#,(?<=-name ".*)(?=.* -title)
#
•(.*?) -
  # new-folder -name "$1" -title "$1" -
#^- (.*?) (?=-|\n)
  # new-markdown -name "$1" -title "$1"

# new-folder -name "" -title ""
# new-markdown -name "" -title "" 

# Push-Location "1.0-hardware-and-system-configuration/1.1-explain-linux-boot-process-concept"
# new-markdown -name "boot-options/UEFI-EFI"           -title "UEFI EFI"          
# new-markdown -name "boot-options/PXE"                -title "PXE"                
# new-markdown -name "boot-options/NFS"                -title "NFS"                
# new-markdown -name "boot-options/Boot-From-ISO"      -title "Boot From ISO"      
# new-markdown -name "boot-options/Boot-From-HTTP-FTP" -title "Boot From HTTP FTP" 

# new-markdown -name "file-locations/etc-default-grub" -title "/etc/default/grub" 
# new-markdown -name "file-locations/etc-grub2-cfg"    -title "/etc/grub2/cfg" 
# new-markdown -name "file-locations/boot"             -title "/boot" 
# new-markdown -name "file-locations/boot-grub"        -title "/boot/grub" 
# new-markdown -name "file-locations/boot-grub2"       -title "/boot/grub2" 
# new-markdown -name "file-locations/boot-efi"         -title "/boot/efi" 

# new-folder -name "boot-modules-and-files/commands" -title "commands"
# new-markdown -name "boot-modules-and-files/commands/mkinitrd"       -title "mkinitrd"       
# new-markdown -name "boot-modules-and-files/commands/dracut"         -title "dracut"          
# new-markdown -name "boot-modules-and-files/commands/grub2-install"  -title "grub2-install"   
# new-markdown -name "boot-modules-and-files/commands/grub2-mkconfig" -title "grub2-mkconfig"  

# new-markdown -name "boot-modules-and-files/initramfs" -title "initramfs"  
# new-markdown -name "boot-modules-and-files/efi-files" -title "efi files"  
# new-markdown -name "boot-modules-and-files/vmlinuz"   -title "vmlinuz"    
# new-markdown -name "boot-modules-and-files/vmlinux"   -title "vmlinux"    
# Pop-Location

# new-folder -name "1.0-hardware-and-system-configuration/1.2-given-a-scenario-install-configure-and-monitor-kernel-modules" -title "given a scenario install configure and monitor kernel modules"
# Push-Location "1.0-hardware-and-system-configuration/1.2-given-a-scenario-install-configure-and-monitor-kernel-modules"

# new-folder -name "commands"   -title "commands"
# new-markdown -name "commands/lsmod"    -title "lsmod"   
# new-markdown -name "commands/insmod"   -title "insmod"  
# new-markdown -name "commands/modprobe" -title "modprobe"
# new-markdown -name "commands/modinfo"  -title "modinfo" 
# new-markdown -name "commands/dmesg"    -title "dmesg"   
# new-markdown -name "commands/rmmod"    -title "rmmod"   
# new-markdown -name "commands/depmod"   -title "depmod"  

# new-folder -name "locations" -title "locations"
# new-markdown -name "locations/usr-lib-modules-[kernelversion]" -title "/usr/lib/modules/[kernelversion]"
# new-markdown -name "locations/usr-lib-modules"                 -title "/usr/lib/modules"
# new-markdown -name "locations/etc-modprobe-conf"               -title "/etc/modprobe.conf"
# new-markdown -name "locations/etc-modprobe-d"                  -title "/etc/modprobe.d"

# Pop-Location

# new-folder -name "1.0-hardware-and-system-configuration/1.3-given-a-scenario-configure-and-verify-network-connection-parameters" -title "given a scenario configure and verify network connection parameters"
# Push-Location "1.0-hardware-and-system-configuration/1.3-given-a-scenario-configure-and-verify-network-connection-parameters"
# new-folder -name "Diagnostic-tools" -title "Diagnostic tools"
# new-markdown -name "Diagnostic-tools/ping" -title "ping"
# new-markdown -name "Diagnostic-tools/netstat" -title "netstat"
# new-markdown -name "Diagnostic-tools/nslookup" -title "nslookup"
# new-markdown -name "Diagnostic-tools/dig" -title "dig"
# new-markdown -name "Diagnostic-tools/host" -title "host"
# new-markdown -name "Diagnostic-tools/route" -title "route"
# new-markdown -name "Diagnostic-tools/ip" -title "ip"
# new-markdown -name "Diagnostic-tools/ethtool" -title "ethtool"
# new-markdown -name "Diagnostic-tools/ss" -title "ss"
# new-markdown -name "Diagnostic-tools/iwconfig" -title "iwconfig"
# new-markdown -name "Diagnostic-tools/nmcli" -title "nmcli"
# new-markdown -name "Diagnostic-tools/brctl" -title "brctl"
# new-markdown -name "Diagnostic-tools/nmtui" -title "nmtui"

# new-folder -name "Configuration-files" -title "Configuration files"
# new-markdown -name "Configuration-files/etc-sysconfig-network-scripts" -title "/etc/sysconfig/network-scripts/"
# new-markdown -name "Configuration-files/etc-sysconfig-network" -title "/etc/sysconfig/network"
# new-markdown -name "Configuration-files/etc-hosts" -title "/etc/hosts"
# new-markdown -name "Configuration-files/etc-network" -title "/etc/network"
# new-markdown -name "Configuration-files/etc-nsswitch-conf" -title "/etc/nsswitch.conf"
# new-markdown -name "Configuration-files/etc-resolv-conf" -title "/etc/resolv.conf"
# new-markdown -name "Configuration-files/etc-netplan" -title "/etc/netplan"
# new-markdown -name "Configuration-files/etc-sysctl-conf" -title "/etc/sysctl.conf"
# new-markdown -name "Configuration-files/etc-dhcp-dhclient-conf" -title "/etc/dhcp/dhclient.conf"

# new-folder -name "Bonding" -title "Bonding"
# new-markdown -name "Bonding/Aggregation" -title "Aggregation"
# new-markdown -name "Bonding/Active-passive" -title "Active/passive"
# new-markdown -name "Bonding/Load-balancing" -title "Load balancing"

# Pop-Location

# new-folder -name "1.0-hardware-and-system-configuration/1.4-given-a-scenario-manage-storage-in-a-linux-environment" -title "given a scenario manage storage in a linux environment"
# Push-Location "1.0-hardware-and-system-configuration/1.4-given-a-scenario-manage-storage-in-a-linux-environment"
 
# new-folder -name "Basic-partitions" -title "Basic partitions"
# new-markdown -name "Basic-partitions/Raw-devices" -title "Raw devices"
# new-markdown -name "Basic-partitions/GPT" -title "GPT"
# new-markdown -name "Basic-partitions/MBR" -title "MBR"

# new-folder -name "File-system-hierarchy" -title "File system hierarchy"
# new-markdown -name "File-system-hierarchy/Real-file-systems" -title "Real file systems"
# new-markdown -name "File-system-hierarchy/Virtual-file-systems" -title "Virtual file systems"
# new-markdown -name "File-system-hierarchy/Relative-paths" -title "Relative paths"
# new-markdown -name "File-system-hierarchy/Absolute-paths" -title "Absolute paths"

# new-folder -name "Device-mapper" -title "Device mapper"
# new-markdown -name "Device-mapper/LVM" -title "LVM"
# new-markdown -name "Device-mapper/mdadm" -title "mdadm"
# new-markdown -name "Device-mapper/Multipath" -title "Multipath"

# new-folder -name "Tools" -title "Tools"
# new-markdown -name "Tools/XFS-tools" -title "XFS tools"
# new-markdown -name "Tools/LVM-tools" -title "LVM tools"
# new-markdown -name "Tools/EXT-tools" -title "EXT tools"

# new-folder -name "Tools/Commands" -title "Commands"
# new-markdown -name "Tools/Commands/mdadm" -title "mdadm"
# new-markdown -name "Tools/Commands/fdisk" -title "fdisk"
# new-markdown -name "Tools/Commands/parted" -title "parted"
# new-markdown -name "Tools/Commands/mkfs" -title "mkfs"
# new-markdown -name "Tools/Commands/iostat" -title "iostat"
# new-markdown -name "Tools/Commands/df" -title "df"
# new-markdown -name "Tools/Commands/du" -title "du"
# new-markdown -name "Tools/Commands/mount" -title "mount"
# new-markdown -name "Tools/Commands/umount" -title "umount"
# new-markdown -name "Tools/Commands/lsblk" -title "lsblk"
# new-markdown -name "Tools/Commands/blkid" -title "blkid"
# new-markdown -name "Tools/Commands/dumpe2fs" -title "dumpe2fs"
# new-markdown -name "Tools/Commands/resize2fs" -title "resize2fs"
# new-markdown -name "Tools/Commands/fsck" -title "fsck"
# new-markdown -name "Tools/Commands/tune2fs" -title "tune2fs"
# new-markdown -name "Tools/Commands/e2label" -title "e2label"

# new-folder -name "Location" -title "Location"
# new-markdown -name "Location/etc-fstab" -title "/etc/fstab"
# new-markdown -name "Location/etc-crypttab" -title "/etc/crypttab"
# new-markdown -name "Location/dev-" -title "/dev/"
# new-markdown -name "Location/dev-mapper" -title "/dev/mapper"

# new-folder -name "Location/dev-disk-by-" -title "/dev/disk/by-"
# new-markdown -name "Location/dev-disk-by-/id-" -title "/dev/disk/by-id"
# new-markdown -name "Location/dev-disk-by-/uuid-" -title "/dev/disk/by-uuid"
# new-markdown -name "Location/dev-disk-by-/path-" -title "/dev/disk/by-path"
# new-markdown -name "Location/dev-disk-by-/multipath" -title "/dev/disk/by-multipath"

# new-markdown -name "Location/etc-mtab" -title "/etc/mtab"
# new-markdown -name "Location/sys-block" -title "/sys/block"
# new-markdown -name "Location/proc-partitions" -title "/proc/partitions"
# new-markdown -name "Location/proc-mounts" -title "/proc/mounts"

# new-folder -name "File-system-types" -title "File system types"
# new-markdown -name "File-system-types/ext3" -title "ext3"
# new-markdown -name "File-system-types/ext4" -title "ext4"
# new-markdown -name "File-system-types/xfs" -title "xfs"
# new-markdown -name "File-system-types/nfs" -title "nfs"
# new-markdown -name "File-system-types/smb" -title "smb"
# new-markdown -name "File-system-types/cifs" -title "cifs"
# new-markdown -name "File-system-types/ntfs" -title "ntfs"


# Pop-Location

# new-folder -name "1.0-hardware-and-system-configuration/1.5-compare-and-contract-cloud-and-virtualization-concepts-and-technologies" -title "compare and contract cloud and virtualization concepts and technologies"
# Push-Location "1.0-hardware-and-system-configuration/1.5-compare-and-contract-cloud-and-virtualization-concepts-and-technologies" 
 
# new-folder -name "Templates" -title "Templates"
# new-markdown -name "Templates/VM" -title "VM"
# new-markdown -name "Templates/OVA" -title "OVA"
# new-markdown -name "Templates/OVF" -title "OVF"
# new-markdown -name "Templates/JSON" -title "JSON"
# new-markdown -name "Templates/YAML" -title "YAML"
# new-markdown -name "Templates/Container-images" -title "Container images"

# new-folder -name "Bootstrapping" -title "Bootstrapping"
# new-markdown -name "Bootstrapping/Cloud-init" -title "Cloud-init"
# new-markdown -name "Bootstrapping/Anaconda" -title "Anaconda"
# new-markdown -name "Bootstrapping/Kickstart" -title "Kickstart"

# new-folder -name "Storage" -title "Storage"
# new-markdown -name "Storage/Thin-vs-thick-provisioning" -title "Thin vs. thick provisioning"
# new-markdown -name "Storage/Persistent-volumes" -title "Persistent volumes"
# new-markdown -name "Storage/Blob" -title "Blob"
# new-markdown -name "Storage/Block" -title "Block"

# new-folder -name "Network-considerations" -title "Network considerations"
# new-markdown -name "Network-considerations/Bridging" -title "Bridging"
# new-markdown -name "Network-considerations/Overlay-networks" -title "Overlay networks"
# new-markdown -name "Network-considerations/NAT" -title "NAT"
# new-markdown -name "Network-considerations/Local" -title "Local"
# new-markdown -name "Network-considerations/Dual-homed" -title "Dual-homed"

# new-markdown -name "Types-of-hypervisors" -title "Types of hypervisors"

# new-folder -name "Tools" -title "Tools"
# new-markdown -name "Tools/libvirt" -title "libvirt"
# new-markdown -name "Tools/virsh" -title "virsh"
# new-markdown -name "Tools/vmm" -title "vmm"

# Pop-Location

# new-folder -name "1.0-hardware-and-system-configuration/1.6-given-a-scenario-configure-localization-options" -title "given a scenario configure localization options"
# Push-Location "1.0-hardware-and-system-configuration/1.6-given-a-scenario-configure-localization-options"
 
# new-folder -name "File-locations" -title "File locations"
# new-markdown -name "File-locations/etc-timezone" -title "/etc/timezone"
# new-markdown -name "File-locations/usr-share-zoneinfo" -title "/usr/share/zoneinfo "

# new-folder -name "Commands" -title "Commands"
# new-markdown -name "Commands/localectl" -title "localectl"
# new-markdown -name "Commands/timedatectl" -title "timedatectl"
# new-markdown -name "Commands/date" -title "date"
# new-markdown -name "Commands/hwclock" -title "hwclock"

# new-folder -name "Environment-variables" -title "Environment variables"
# new-markdown -name "Environment-variables/LC_star" -title "LC_*"
# new-markdown -name "Environment-variables/LC_ALL" -title "LC_ALL"
# new-markdown -name "Environment-variables/LANG" -title "LANG"
# new-markdown -name "Environment-variables/TZ" -title "TZ"
 
 
# new-folder -name "Character-sets" -title "Character sets"
# new-markdown -name "Character-sets/UTF-8" -title "UTF-8"
# new-markdown -name "Character-sets/ASCII" -title "ASCII"
# new-markdown -name "Character-sets/Unicode" -title "Unicode"

# Pop-Location

# new-folder -name "2.0-systems-operation-and-maintenance/2.1-Given-a-scenario-conduct-software-installations-configurations-updates-and-removals" -title "Given a scenario, conduct software installations, configurations, updates, and removals"
# Push-Location "2.0-systems-operation-and-maintenance/2.1-Given-a-scenario-conduct-software-installations-configurations-updates-and-removals"
 
# new-folder -name "Package-types" -title "Package types"
# new-markdown -name "Package-types/rpm" -title ".rpm"
# new-markdown -name "Package-types/deb" -title ".deb"
# new-markdown -name "Package-types/tar" -title ".tar"
# new-markdown -name "Package-types/tgz" -title ".tgz"
# new-markdown -name "Package-types/gz" -title ".gz"

# new-folder -name "Installation-tools" -title "Installation tools"
# new-markdown -name "Installation-tools/RPM" -title "RPM"
# new-markdown -name "Installation-tools/Dpkg" -title "Dpkg"
# new-markdown -name "Installation-tools/APT" -title "APT"
# new-markdown -name "Installation-tools/YUM" -title "YUM"
# new-markdown -name "Installation-tools/DNF" -title "DNF"
# new-markdown -name "Installation-tools/Zypper" -title "Zypper"

# new-folder -name "Build-tools" -title "Build tools"
# new-folder -name "Build-tools/Commands" -title "Commands"
# new-markdown -name "Build-tools/Commands/make" -title "make"
# new-markdown -name "Build-tools/Commands/make-install" -title "make install"
# new-markdown -name "Build-tools/Commands/ldd" -title "ldd"
# new-markdown -name "Build-tools/Compilers" -title "Compilers"
# new-markdown -name "Build-tools/Shared-libraries" -title "Shared libraries"
 
# new-folder -name "Repositories" -title "Repositories"
# new-markdown -name "Repositories/Configuration" -title "Configuration"
# new-markdown -name "Repositories/Creation" -title "Creation"
# new-markdown -name "Repositories/Syncing" -title "Syncing"
# new-markdown -name "Repositories/Locations" -title "Locations"

# new-folder -name "Acquisition-commands" -title "Acquisition commands"
# new-markdown -name "wget" -title "wget"
# new-markdown -name "curl" -title "curl"

# Pop-Location

# new-folder -name "2.0-systems-operation-and-maintenance/2.2-Given-a-scenario-manage-users-and-groups" -title "Given a scenario, manage users and groups"
# Push-Location "2.0-systems-operation-and-maintenance/2.2-Given-a-scenario-manage-users-and-groups"
 
# new-folder -name "Creation" -title "Creation"
# new-markdown -name "Creation/useradd" -title "useradd"
# new-markdown -name "Creation/groupadd" -title "groupadd"

# new-folder -name "Modification" -title "Modification"
# new-markdown -name "Modification/usermod" -title "usermod"
# new-markdown -name "Modification/groupmod" -title "groupmod"
# new-markdown -name "Modification/passwd" -title "passwd"
# new-markdown -name "Modification/chage" -title "chage"

# new-folder -name "Deletion" -title "Deletion"
# new-markdown -name "Deletion/userdel" -title "userdel"
# new-markdown -name "Deletion/groupdel" -title "groupdel"
 
# new-folder -name "Queries" -title "Queries"
# new-markdown -name "Queries/id" -title "id"
# new-markdown -name "Queries/whoami" -title "whoami"
# new-markdown -name "Queries/who" -title "who"
# new-markdown -name "Queries/w" -title "w"
# new-markdown -name "Queries/last" -title "last"

# new-folder -name "Quotas" -title "Quotas"
# new-markdown -name "Quotas/User-quota" -title "User quota"
# new-markdown -name "Quotas/Group-quota" -title "Group quota"

# new-folder -name "Profiles" -title "Profiles"
# new-folder -name "Profiles/Bash-parameters" -title "Bash parameters"

# new-folder -name "Profiles/Bash-parameters/User-entries" -title "User entries"
# new-markdown -name "Profiles/Bash-parameters/User-entries/bashrc" -title ".bashrc"
# new-markdown -name "Profiles/Bash-parameters/User-entries/bash_profile" -title ".bash_profile"
# new-markdown -name "Profiles/Bash-parameters/User-entries/profile" -title ".profile"

# new-folder -name "Profiles/Bash-parameters/Global-entries" -title "Global entries"
# new-markdown -name "Profiles/Bash-parameters/Global-entries/etc-bashrc" -title "/etc/bashrc"
# new-markdown -name "Profiles/Bash-parameters/Global-entries/etc-profile-d" -title "/etc/profile.d/"
# new-markdown -name "Profiles/Bash-parameters/Global-entries/etc-skel" -title "/etc/skel"
# new-markdown -name "Profiles/Bash-parameters/Global-entries/etc-profile" -title "/etc/profile"

# new-folder -name "Important-files-and-file-contents" -title "Important files and file contents"
# new-markdown -name "Important-files-and-file-contents/etc-passwd" -title "/etc/passwd"
# new-markdown -name "Important-files-and-file-contents/etc-group" -title "/etc/group"
# new-markdown -name "Important-files-and-file-contents/etc-shadow" -title "/etc/shadow"

# Pop-Location

# new-folder -name "2.0-systems-operation-and-maintenance/2.3-Given-a-scenario-create-modify-and-redirect-files" -title "Given a scenario, create, modify, and redirect files"
# Push-Location "2.0-systems-operation-and-maintenance/2.3-Given-a-scenario-create-modify-and-redirect-files" 
 
# new-folder -name "Text-editors" -title "Text editors"
# new-markdown -name "Text-editors/nano" -title "nano"
# new-markdown -name "Text-editors/vi" -title "vi "

# new-folder -name "File-readers" -title "File readers"
# new-markdown -name "File-readers/grep" -title "grep"
# new-markdown -name "File-readers/cat" -title "cat"
# new-markdown -name "File-readers/tail" -title "tail"
# new-markdown -name "File-readers/head" -title "head"
# new-markdown -name "File-readers/less" -title "less"
# new-markdown -name "File-readers/more" -title "more "

# new-folder -name "Output-redirection" -title "Output redirection"
# new-markdown -name "Output-redirection/<" -title "<"
# new-markdown -name "Output-redirection/>" -title ">"
# new-markdown -name "Output-redirection/|" -title "|"
# new-markdown -name "Output-redirection/<<" -title "<<"
# new-markdown -name "Output-redirection/>>" -title ">>"
# new-markdown -name "Output-redirection/2>" -title "2>"
# new-markdown -name "Output-redirection/&>" -title "&>"
# new-markdown -name "Output-redirection/stdin" -title "stdin"
# new-markdown -name "Output-redirection/stdout" -title "stdout"
# new-markdown -name "Output-redirection/stderr" -title "stderr"
# new-markdown -name "Output-redirection/dev-null" -title "/dev/null"
# new-markdown -name "Output-redirection/dev-tty" -title "/dev/tty"
# new-markdown -name "Output-redirection/xargs" -title "xargs"
# new-markdown -name "Output-redirection/tee" -title "tee"
# new-markdown -name "Output-redirection/Here-documents" -title "Here documents"

# new-folder -name "Text-processing" -title "Text processing"
# new-markdown -name "Text-processing/grep" -title "grep"
# new-markdown -name "Text-processing/tr" -title "tr"
# new-markdown -name "Text-processing/echo" -title "echo"
# new-markdown -name "Text-processing/sort" -title "sort"
# new-markdown -name "Text-processing/awk" -title "awk"
# new-markdown -name "Text-processing/sed" -title "sed"
# new-markdown -name "Text-processing/cut" -title "cut"
# new-markdown -name "Text-processing/printf" -title "printf"
# new-markdown -name "Text-processing/egrep" -title "egrep"
# new-markdown -name "Text-processing/wc" -title "wc"
# new-markdown -name "Text-processing/paste" -title "paste" 

# new-folder -name "File-and-directory-operations" -title "File and directory operations"
# new-markdown -name "File-and-directory-operations/touch" -title "touch"
# new-markdown -name "File-and-directory-operations/mv" -title "mv"
# new-markdown -name "File-and-directory-operations/cp" -title "cp"
# new-markdown -name "File-and-directory-operations/rm" -title "rm"
# new-markdown -name "File-and-directory-operations/scp" -title "scp"
# new-markdown -name "File-and-directory-operations/ls" -title "ls"
# new-markdown -name "File-and-directory-operations/rsync" -title "rsync"
# new-markdown -name "File-and-directory-operations/mkdir" -title "mkdir"
# new-markdown -name "File-and-directory-operations/rmdir" -title "rmdir"
# new-folder -name "File-and-directory-operations/ln" - title "ln"
# new-markdown -name "File-and-directory-operations/ln/Symbolic-soft" -title "Symbolic (soft)"
# new-markdown -name "File-and-directory-operations/ln/Hard" -title "Hard"

# new-markdown -name "File-and-directory-operations/unlink" -title "unlink"
# new-markdown -name "File-and-directory-operations/inodes" -title "inodes"
# new-markdown -name "File-and-directory-operations/find" -title "find"
# new-markdown -name "File-and-directory-operations/locate" -title "locate"
# new-markdown -name "File-and-directory-operations/grep" -title "grep"
# new-markdown -name "File-and-directory-operations/which" -title "which"
# new-markdown -name "File-and-directory-operations/whereis" -title "whereis"
# new-markdown -name "File-and-directory-operations/diff" -title "diff"
# new-markdown -name "File-and-directory-operations/updatedb" -title "updatedb"

# Pop-Location

new-folder -name "2.0-systems-operation-and-maintenance/2.4-Given-a-scenario-manage-services" -title "Given a scenario, manage services"
Push-Location "2.0-systems-operation-and-maintenance/2.4-Given-a-scenario-manage-services"
new-folder -name "Systemd-management" -title "Systemd management"
  new-folder -name "Systemd-management/Systemctl" -title "Systemctl"
    new-markdown -name "Systemd-management/Systemctl/Enabled" -title "Enabled"
    new-markdown -name "Systemd-management/Systemctl/Disabled" -title "Disabled"
    new-markdown -name "Systemd-management/Systemctl/Start" -title "Start"
    new-markdown -name "Systemd-management/Systemctl/Stop" -title "Stop"
    new-markdown -name "Systemd-management/Systemctl/Mask" -title "Mask"
    new-markdown -name "Systemd-management/Systemctl/Restart" -title "Restart"
    new-markdown -name "Systemd-management/Systemctl/Status" -title "Status"
    new-markdown -name "Systemd-management/Systemctl/Daemon-reload" -title "Daemon-reload"
  new-markdown -name "Systemd-management/Systemd-analyze-blame" -title "Systemd-analyze blame"
  new-folder -name "Systemd-management/Unit-files" -title "unit files"
    new-markdown -name "Systemd-management/Unit-files/Directory-locations" -title "Directory locations"
    new-markdown -name "Systemd-management/Unit-files/Environment-parameters" -title "Environment parameters"
    new-markdown -name "Systemd-management/Unit-files/Targets" -title "Targets"
    new-markdown -name "Systemd-management/Unit-files/Hostnamectl" -title "Hostnamectl"
    new-markdown -name "Systemd-management/Unit-files/Automount" -title "Automount"
new-folder -name "SysVinit" -title "SysVinit"
  new-folder -name "SysVinit/chkconfig" -title "chkconfig"
    new-markdown -name "SysVinit/chkconfig/on" -title "on"
    new-markdown -name "SysVinit/chkconfig/off" -title "off"
    new-markdown -name "SysVinit/chkconfig/level" -title "level"
  new-folder -name "SysVinit/Runlevels" -title "Runlevels"
    new-markdown -name "SysVinit/Runlevels/Definitions-of-0–6" -title "Definitions of 0–6"
    new-markdown -name "SysVinit/Runlevels/etc-init-d" -title "/etc/init.d"
    new-markdown -name "SysVinit/Runlevels/etc-rc-d" -title "/etc/rc.d"
    new-markdown -name "SysVinit/Runlevels/etc-rc-local" -title "/etc/rc.local"
    new-markdown -name "SysVinit/Runlevels/etc-inittab" -title "/etc/inittab"
    new-folder -name "SysVinit/Runlevels/Commands" -title "Commands"
      new-markdown -name "SysVinit/Runlevels/Commands/runlevel" -title "runlevel"
      new-markdown -name "SysVinit/Runlevels/Commands/telinit" -title "runlevel"
  new-folder -name "SysVinit/Service" -title "Service"
    new-markdown -name "SysVinit/Service/Restart" -title "Restart"
    new-markdown -name "SysVinit/Service/Status"  -title "Status"
    new-markdown -name "SysVinit/Service/Stop"    -title "Stop"
    new-markdown -name "SysVinit/Service/Start"   -title "Start"
    new-markdown -name "SysVinit/Service/Reload"  -title "Reload" 
Pop-Location

new-folder -name "2.0-systems-operation-and-maintenance/2.5-Summarize-and-explain-server-roles" -title "Summarize and explain server roles"
Push-Location "2.0-systems-operation-and-maintenance/2.5-Summarize-and-explain-server-roles"
  new-markdown -name "NTP" -title "NTP"
  new-markdown -name "SSH" -title "SSH"
  new-markdown -name "Web" -title "Web"
  new-markdown -name "Certificate-authority" -title "Certificate authority"
  new-markdown -name "Name-server" -title "Name server"
  new-markdown -name "DHCP" -title "DHCP"
  new-markdown -name "File-servers" -title "File servers"
  new-markdown -name "Authentication-server" -title "Authentication server"
  new-markdown -name "Proxy" -title "Proxy"
  new-markdown -name "Logging" -title "Logging"
  new-markdown -name "Containers" -title "Containers"
  new-markdown -name "VPN" -title "VPN"
  new-markdown -name "Monitoring" -title "Monitoring"
  new-markdown -name "Database" -title "Database"
  new-markdown -name "Print-server" -title "Print server"
  new-markdown -name "Mail-server" -title "Mail server"
  new-markdown -name "Load-balancer" -title "Load balancer"
  new-markdown -name "Clustering" -title "Clustering"
Pop-Location

new-folder -name "2.0-systems-operation-and-maintenance/2.6-Given-a-scenario-automate-and-schedule-jobs" -title "Given a scenario, automate and schedule jobs"
Push-Location "2.0-systems-operation-and-maintenance/2.6-Given-a-scenario-automate-and-schedule-jobs"
  new-markdown -name "cron" -title "cron"
  new-markdown -name "at" -title "at"
  new-markdown -name "crontab" -title "crontab"
  new-markdown -name "fg" -title "fg"
  new-markdown -name "bg" -title "bg"
  new-markdown -name "kill" -title "kill"
  new-markdown -name "Ctrl-c" -title "Ctrl+c"
  new-markdown -name "Ctrl-z" -title "Ctrl+z"
  new-markdown -name "nohup" -title "nohup"
Pop-Location

new-folder -name "2.0-systems-operation-and-maintenance/2.7-Explain-the-use-and-operation-of-Linux-devices" -title "Explain the use and operation of Linux devices"
Push-Location "2.0-systems-operation-and-maintenance/2.7-Explain-the-use-and-operation-of-Linux-devices"
  new-folder -name "Types-of-devices" -title "Types of devices"
    new-markdown -name "Types-of-devices/Client-devices" -title "Client devices"
    new-markdown -name "Types-of-devices/Bluetooth" -title "Bluetooth"
    new-markdown -name "Types-of-devices/WiFi" -title "WiFi"
    new-markdown -name "Types-of-devices/USB" -title "USB"
    new-markdown -name "Types-of-devices/Monitors" -title "Monitors"
    new-markdown -name "Types-of-devices/GPIO" -title "GPIO"
    new-markdown -name "Types-of-devices/Network-adapters" -title "Network adapters"
    new-markdown -name "Types-of-devices/PCI" -title "PCI"
    new-markdown -name "Types-of-devices/HBA" -title "HBA"
    new-markdown -name "Types-of-devices/SATA" -title "SATA"
    new-markdown -name "Types-of-devices/SCSI" -title "SCSI"
    new-markdown -name "Types-of-devices/Printers" -title "Printers"
    new-markdown -name "Types-of-devices/Video" -title "Video"
    new-markdown -name "Types-of-devices/Audio" -title "Audio"
  
  new-folder -name "Monitoring-and-configuration-tools" -title "Monitoring and configuration tools"
    new-markdown -name "Monitoring-and-configuration-tools/lsdev" -title "lsdev"
    new-markdown -name "Monitoring-and-configuration-tools/lsusb" -title "lsusb"
    new-markdown -name "Monitoring-and-configuration-tools/lspci" -title "lspci"
    new-markdown -name "Monitoring-and-configuration-tools/lsblk" -title "lsblk"
    new-markdown -name "Monitoring-and-configuration-tools/dmesg" -title "dmesg"
    new-markdown -name "Monitoring-and-configuration-tools/lpr" -title "lpr"
    new-markdown -name "Monitoring-and-configuration-tools/lpq" -title "lpq"
    new-markdown -name "Monitoring-and-configuration-tools/abrt" -title "abrt"
    new-markdown -name "Monitoring-and-configuration-tools/CUPS" -title "CUPS"
    new-folder -name "Monitoring-and-configuration-tools/udevadm"
      new-markdown -name "Monitoring-and-configuration-tools/udevadm/add" -title "add"
      new-markdown -name "Monitoring-and-configuration-tools/udevadm/reload-rules" -title "reload-rules"
      new-markdown -name "Monitoring-and-configuration-tools/udevadm/control" -title "control"
      new-markdown -name "Monitoring-and-configuration-tools/udevadm/trigger" -title "trigger"
  new-folder -name "File-locations" -title "File locations"
    new-markdown -name "File-locations/proc" -title "/proc"
    new-markdown -name "File-locations/sys" -title "/sys"
    new-markdown -name "File-locations/dev" -title "/dev"
    new-markdown -name "File-locations/dev-mapper" -title "/dev/mapper"
    new-markdown -name "File-locations/etc-X11" -title "/etc/X11"
  new-folder -name "Hot-pluggable-devices" -title "Hot pluggable devices"
    new-markdown -name "Hot-pluggable-devices/usr-lib-udev-rules-d-System-rules" -title "/usr/lib/udev/rules.d (System rules Lowest-priority)"
    new-markdown -name "Hot-pluggable-devices/run-udev-rules-d-Volatile-Rules" -title "/run/udev/rules.d (Volatile Rules)"
    new-markdown -name "Hot-pluggable-devices/etc-udev-rules-d-Local-Administration-Highest-priority" -title "/etc/udev/rules.d (Local Administration Highest-priority)"
    new-markdown -name "Hot-pluggable-devices/etc-udev-rules-d" -title "/etc/udev/rules.d"
Pop-Location

new-folder -name "2.0-systems-operation-and-maintenance/2.8-Compare-and-contrast-Linux-graphical-user-interfaces." -title "Compare and contrast Linux graphical user interfaces."
Push-Location "2.0-systems-operation-and-maintenance/2.8-Compare-and-contrast-Linux-graphical-user-interfaces."
  new-folder -name "Servers" -title "Servers"
    new-markdown -name "Servers/Wayland" -title "Wayland"
    new-markdown -name "Servers/X11" -title "X11"
  new-folder -name "GUI" -title "GUI"
    new-markdown -name "GUI/Gnome" -title "Gnome"
    new-markdown -name "GUI/Unity" -title "Unity"
    new-markdown -name "GUI/Cinnamon" -title "Cinnamon"
    new-markdown -name "GUI/MATE" -title "MATE"
    new-markdown -name "GUI/KDE" -title "KDE"
  new-folder -name "Remote-desktop" -title "Remote desktop"
    new-markdown -name "Remote-desktop/VNC" -title "VNC"
    new-markdown -name "Remote-desktop/XRDP" -title "XRDP"
    new-markdown -name "Remote-desktop/NX" -title "NX"
    new-markdown -name "Remote-desktop/Spice" -title "Spice"
  new-folder -name "Console-redirection" -title "Console redirection"
    new-folder -name "Console-redirection/SSH-port-forwarding" -title "SSH port forwarding "
      new-markdown -name "Console-redirection/SSH-port-forwarding/Local" -title "Local "
      new-markdown -name "Console-redirection/SSH-port-forwarding/Remote" -title "Remote "
      new-markdown -name "Console-redirection/SSH-port-forwarding/X11-forwarding" -title "X11 forwarding "
      new-markdown -name "Console-redirection/SSH-port-forwarding/VNC" -title "VNC"
      new-markdown -name "Console-redirection/SSH-port-forwarding/Accessibility" -title "Accessibility"
Pop-Location


new-folder -name "3.0-security/3.1-Summarize-security-best-practices-in-a-Linux-environment" -title "Summarize security best practices in a Linux environment."
Push-Location "3.0-security/3.1-Summarize-security-best-practices-in-a-Linux-environment"
  new-folder -name "File-and-directory-permissions" -title "File and directory permissions"
    new-markdown -name "File-and-directory-permissions/Read-write-execute" -title "Read, write, execute"
    new-markdown -name "File-and-directory-permissions/User-group-other" -title "User, group, other"
    new-markdown -name "File-and-directory-permissions/SUID" -title "SUID"
    new-markdown -name "File-and-directory-permissions/Octal-notation" -title "Octal notation"
    new-markdown -name "File-and-directory-permissions/umask" -title "umask"
    new-markdown -name "File-and-directory-permissions/Sticky-bit" -title "Sticky bit"
    new-markdown -name "File-and-directory-permissions/SGID" -title "SGID"
    new-markdown -name "File-and-directory-permissions/Inheritance" -title "Inheritance"
    new-folder -name "File-and-directory-permissions/Utilities" -title "Utilities"
      new-markdown -name "File-and-directory-permissions/Utilities/chmod" -title "chmod"
      new-markdown -name "File-and-directory-permissions/Utilities/chown" -title "chown"
      new-markdown -name "File-and-directory-permissions/Utilities/chgrp" -title "chgrp"
      new-markdown -name "File-and-directory-permissions/Utilities/getfacl" -title "getfacl"
      new-markdown -name "File-and-directory-permissions/Utilities/setfacl" -title "setfacl"
      new-markdown -name "File-and-directory-permissions/Utilities/ls" -title "ls"
      new-markdown -name "File-and-directory-permissions/Utilities/ulimit" -title "ulimit"
      new-markdown -name "File-and-directory-permissions/Utilities/chage" -title "chage"
  new-folder -name "Context-based-permissions" -title "Context-based permissions"
    new-folder -name "Context-based-permissions/SELinux-configurations" -title "SELinux configurations"
      new-markdown -name "Context-based-permissions/SELinux-configurations/disabled" -title "disabled"
      new-markdown -name "Context-based-permissions/SELinux-configurations/permissive" -title "permissive"
      new-markdown -name "Context-based-permissions/SELinux-configurations/enforcing" -title "enforcing"
    new-folder -name "Context-based-permissions/SELinux-policy" -title "SELinux policy"
      new-markdown -name "Context-based-permissions/SELinux-policy/targeted" -title "targeted"
    new-folder -name "Context-based-permissions/SELinux-tools" -title "SELinux tools"
      new-markdown -name "Context-based-permissions/SELinux-tools/setenforce" -title "setenforce"
      new-markdown -name "Context-based-permissions/SELinux-tools/getenforce" -title "getenforce"
      new-markdown -name "Context-based-permissions/SELinux-tools/sestatus" -title "sestatus"
      new-markdown -name "Context-based-permissions/SELinux-tools/setsebool" -title "setsebool"
      new-markdown -name "Context-based-permissions/SELinux-tools/getsebool" -title "getsebool"
      new-markdown -name "Context-based-permissions/SELinux-tools/chcon" -title "chcon"
      new-markdown -name "Context-based-permissions/SELinux-tools/restorecon" -title "restorecon"
      new-markdown -name "Context-based-permissions/SELinux-tools/ls-z" -title "ls -Z"
      new-markdown -name "Context-based-permissions/SELinux-tools/pz-z" -title "pz -Z"
      new-folder -name "Context-based-permissions/SELinux-tools/AppArmor" -title "AppArmor"
        new-markdown -name "Context-based-permissions/SELinux-tools/AppArmor/aa-disable" -title "aa-disable"
        new-markdown -name "Context-based-permissions/SELinux-tools/AppArmor/aa-complain" -title "aa-complain"
        new-markdown -name "Context-based-permissions/SELinux-tools/AppArmor/aa-unconfined" -title "aa-unconfined"
        new-markdown -name "Context-based-permissions/SELinux-tools/AppArmor/etc-apparmor-d" -title "/etc/apparmor.d/"
        new-markdown -name "Context-based-permissions/SELinux-tools/AppArmor/etc-apparmor-d-tunables" -title "/etc/apparmor.d/tunables"
  new-folder -name "Privilege-escalation" -title "Privilege escalation"
    new-markdown -name "Privilege-escalation/su" -title "su"
    new-markdown -name "Privilege-escalation/sudo" -title "sudo"
    new-markdown -name "Privilege-escalation/wheel" -title "wheel"
    new-markdown -name "Privilege-escalation/visudo" -title "visudo"
    new-markdown -name "Privilege-escalation/sudoedit" -title "sudoedit"
  new-folder -name "User-types" -title "User types"
    new-markdown -name "User-types/Root" -title "Root"
    new-markdown -name "User-types/Standard" -title "Standard"
    new-markdown -name "User-types/Service" -title "Service"
Pop-Location

new-folder -name "3.0-security/3.2-Given-a-scenario-configure-and-implement-appropriate-access-and-authentication-methods" -title "Given a scenario, configure and implement appropriate access and authentication methods."
Push-Location "3.0-security/3.2-Given-a-scenario-configure-and-implement-appropriate-access-and-authentication-methods"
  new-folder -name "PAM" -title "PAM"
    new-markdown -name "PAM/Password-policies" -title "Password policies"
    new-markdown -name "PAM/LDAP-integration" -title "LDAP integration"
    new-markdown -name "PAM/User-lockouts" -title "User lockouts"
    new-markdown -name "PAM/Required-optional-or-sufficient" -title "Required, optional, or sufficient"
    new-markdown -name "PAM/etc-pam-d" -title "/etc/pam.d/"
    new-markdown -name "PAM/pam-tally2" -title "pam_tally2"
    new-markdown -name "PAM/faillock" -title "faillock"
  new-folder -name "SSH" -title "SSH"
    new-folder -name "SSH/ssh" -title "~/.ssh/"
      new-markdown -name "SSH/ssh/known_hosts" -title "known_hosts"
      new-markdown -name "SSH/ssh/authorized_keys" -title "authorized_keys"
      new-markdown -name "SSH/ssh/config" -title "config"
      new-markdown -name "SSH/ssh/id-rsa" -title "id_rsa"
      new-markdown -name "SSH/ssh/id-rsa-pub" -title "id_rsa.pub"
    new-markdown -name "SSH/User-specific-access" -title "User-specific access"
    new-markdown -name "SSH/TCP-wrappers" -title "TCP wrappers"
    new-folder -name "SSH/etc-ssh" -title "/etc/ssh/"
      new-markdown -name "SSH/etc-ssh/ssh-config" -title "ssh_config"
      new-markdown -name "SSH/etc-ssh/sshd-config" -title "sshd_config"
    new-markdown -name "SSH/ssh-copy-id" -title "ssh-copy-id"
    new-markdown -name "SSH/ssh-keygen" -title "ssh-keygen"
    new-markdown -name "SSH/ssh-add" -title "ssh-add"
  new-folder -name "TTYs" -title "TTYs"
    new-markdown -name "TTYs/etc-securetty" -title "/etc/securetty"
    new-markdown -name "TTYs/dev-tty" -title "/dev/tty#"
  new-markdown -name "PTYs" -title "PTYs"
  new-folder -name "PKI" -title "PKI"
    new-markdown -name "PKI/Self-signed" -title "Self-signed"
    new-markdown -name "PKI/Private-keys" -title "Private keys"
    new-markdown -name "PKI/Public-keys" -title "Public keys"
    new-markdown -name "PKI/Hashing" -title "Hashing"
    new-markdown -name "PKI/Digital-signatures" -title "Digital signatures"
    new-markdown -name "PKI/Message-digest" -title "Message digest"
  new-folder -name "VPN-as-a-client" -title "VPN as a client"
    new-markdown -name "VPN-as-a-client/SSL-TLS" -title "SSL/TLS"
    new-markdown -name "VPN-as-a-client/Transport-mode" -title "Transport mode"
    new-markdown -name "VPN-as-a-client/Tunnel-mode" -title "Tunnel mode"
    new-markdown -name "VPN-as-a-client/IPSec" -title "IPSec"
    new-markdown -name "VPN-as-a-client/DTLS" -title "DTLS"
Pop-Location

new-folder -name "3.0-security/3.3-Given-a-scenario-apply-or-acquire-the-appropriate-user-and/or-group-permissions-and-ownership" -title "Given a scenario, apply or acquire the appropriate user and/or group permissions and ownership."
Push-Location "3.0-security/3.3-Given-a-scenario-apply-or-acquire-the-appropriate-user-and/or-group-permissions-and-ownership"
  new-folder -name "Boot-security" -title "Boot security"
    new-markdown -name "Boot-security/Boot-loader-password" -title "Boot loader password"
    new-markdown -name "Boot-security/UEFI-BIOS-password" -title "UEFI/BIOS password"
  new-folder -name "Additional-authentication-methods" -title "Additional authentication methods"
    new-folder -name "Additional-authentication-methods/Multifactor-authentication" -title "Multifactor authentication"
      new-folder -name "Additional-authentication-methods/Multifactor-authentication/Tokens" -title "Tokens"
        new-markdown -name "Additional-authentication-methods/Multifactor-authentication/Tokens/Hardware" -title "Hardware"
        new-markdown -name "Additional-authentication-methods/Multifactor-authentication/Tokens/Software" -title "Software"
      new-markdown -name "Additional-authentication-methods/Multifactor-authentication/OTP" -title "OTP"
      new-markdown -name "Additional-authentication-methods/Multifactor-authentication/Biometrics" -title "Biometrics"
    new-markdown -name "Additional-authentication-methods/RADIUS" -title "RADIUS"
    new-markdown -name "Additional-authentication-methods/TACACS" -title "TACACS+"
    new-markdown -name "Additional-authentication-methods/LDAP" -title "LDAP"
    new-folder -name "Additional-authentication-methods/Kerberos" -title "Kerberos"
      new-markdown -name "Additional-authentication-methods/Kerberos/kinit" -title "kinit"
      new-markdown -name "Additional-authentication-methods/Kerberos/klist" -title "klist"
  new-markdown -name "Importance-of-disabling-root-login-via-SSH" -title "Importance of disabling root login via SSH"
  new-folder -name "Password-less-login" -title "Password-less login"
    new-markdown -name "Password-less-login/Enforce-use-of-PKI" -title "Enforce use of PKI"
  new-markdown -name "Chroot-jail-services" -title "Chroot jail services"
  new-markdown -name "No-shared-IDs" -title "No shared IDs"
  new-markdown -name "Importance-of-denying-hosts" -title "Importance of denying hosts"
  new-folder -name "Separation-of-OS-data-from-application-data" -title "Separation of OS data from application data"
    new-markdown -name "Separation-of-OS-data-from-application-data/Disk-partition-to-maximize-system-availability" -title "Disk partition to maximize system availability"
  new-markdown -name "Change-default-ports" -title "Change default ports"
  new-folder -name "Importance-of-disabling-or-uninstalling-unused-and-unsecure-services" -title "Importance of disabling or uninstalling unused and unsecure services"
    new-markdown -name "Importance-of-disabling-or-uninstalling-unused-and-unsecure-services/FTP" -title "FTP"
    new-markdown -name "Importance-of-disabling-or-uninstalling-unused-and-unsecure-services/Telnet" -title "Telnet"
    new-markdown -name "Importance-of-disabling-or-uninstalling-unused-and-unsecure-services/Finger" -title "Finger"
    new-markdown -name "Importance-of-disabling-or-uninstalling-unused-and-unsecure-services/Sendmail" -title "Sendmail"
    new-markdown -name "Importance-of-disabling-or-uninstalling-unused-and-unsecure-services/Postfix" -title "Postfix"
  new-markdown -name "Importance-of-enabling-SSL-TLS" -title "Importance of enabling SSL/TLS"
  new-markdown -name "Importance-of-enabling-auditd" -title "Importance of enabling auditd"
  new-markdown -name "CVE-monitoring" -title "CVE monitoring"
  new-markdown -name "Discouraging-use-of-USB-devices" -title "Discouraging use of USB devices"
  new-folder -name "Disk-encryption" -title "Disk encryption"
    new-markdown -name "Disk-encryption/LUKS" -title "LUKS"
  new-markdown -name "Restrict-cron-access" -title "Restrict cron access"
  new-markdown -name "Disable-Ctrl-Alt-Del" -title "Disable Ctrl+Alt+Del"
  new-markdown -name "Add-banner" -title "Add banner"
  new-markdown -name "MOTD" -title "MOTD"
Pop-Location

new-folder -name "3.0-security/3.4-given-a-scenario-implement-logging-services" -title "given a scenario implement logging services"
Push-Location "3.0-security/3.4-given-a-scenario-implement-logging-services"
  new-folder -name "Key-file-locations" -title "Key file locations"
    new-markdown -name "Key-file-locations/var-log-secure" -title "/var/log/secure"
    new-markdown -name "Key-file-locations/var-log-messages" -title "/var/log/messages"
    new-markdown -name "Key-file-locations/var-log-application" -title "/var/log/[application]"
    new-markdown -name "Key-file-locations/var-log-kern" -title "/var/log/kern.log"
  new-folder -name "Log-management" -title "Log management"
    new-markdown -name "Log-management/Third-party-agents" -title "Third-party agents"
    new-markdown -name "Log-management/logrotate" -title "logrotate"
    new-markdown -name "Log-management/etc-rsyslog-conf" -title "/etc/rsyslog.conf"
    new-folder -name "Log-management/journald" -title "journald"
      new-markdown -name "Log-management/journald/journalctl" -title "journalctl"
  new-markdown -name "lastb" -title "lastb"
Pop-Location

new-folder -name "3.0-security/3.5-given-a-scenario-implement-and-configure-linux-firewalls" -title "given a scenario implement and configure linux firewalls"
Push-Location "3.0-security/3.5-given-a-scenario-implement-and-configure-linux-firewalls"
  new-folder -name "Access-control-lists" -title "Access control lists"
    new-markdown -name "Access-control-lists/Source" -title "Source"
    new-markdown -name "Access-control-lists/Destination" -title "Destination"
    new-markdown -name "Access-control-lists/Ports" -title "Ports"
    new-markdown -name "Access-control-lists/Protocol" -title "Protocol"
    new-markdown -name "Access-control-lists/Logging" -title "Logging"
    new-markdown -name "Access-control-lists/Stateful-vs-stateless" -title "Stateful vs. stateless"
    new-markdown -name "Access-control-lists/Accept" -title "Accept"
    new-markdown -name "Access-control-lists/Reject" -title "Reject"
    new-markdown -name "Access-control-lists/Drop" -title "Drop"
    new-markdown -name "Access-control-lists/Log" -title "Log"
  new-folder -name "Technologies" -title "Technologies"
    new-folder -name "Technologies/firewalld" -title "firewalld"
      new-markdown -name "Technologies/firewalld/Zones" -title "Zones"
      new-markdown -name "Technologies/firewalld/Run-time" -title "Run time"
    new-folder -name "Technologies/iptables" -title "ufw"
      new-markdown -name "Technologies/iptables/Persistency" -title "Persistency"
      new-markdown -name "Technologies/iptables/Chains" -title "Chains"
    new-folder -name "Technologies/ufw" -title "ufw"
      new-markdown -name "Technologies/ufw/etc-default-ufw" -title "/etc/default/ufw"
      new-markdown -name "Technologies/ufw/etc-ufw" -title "/etc/ufw/"
    new-markdown -name "Technologies/Netfilter" -title "netfilter"
  new-folder -name "IP-forwarding" -title "IP forwarding"
    new-markdown -name "IP-forwarding/proc-sys-net-ipv4-ip-forward" -title "/proc/sys/net/ipv4/ip_forward"
    new-markdown -name "IP-forwarding/proc-sys-net-ipv6-conf-all-forwarding" -title "/proc/sys/net/ipv6/conf/all/forwarding "
  new-folder -name "Dynamic-rule-sets" -title "Dynamic rule sets"
    new-markdown -name "Dynamic-rule-sets/DenyHosts" -title "DenyHosts"
    new-markdown -name "Dynamic-rule-sets/Fail2ban" -title "Fail2ban"
    new-markdown -name "Dynamic-rule-sets/IPset" -title "IPset"
  new-folder -name "Common-application-firewall-configurations" -title "Common application firewall configurations"
    new-markdown -name "Common-application-firewall-configurations/etc-services" -title "/etc/services"
    new-markdown -name "Common-application-firewall-configurations/Privileged-ports" -title "Privileged ports"
Pop-Location

new-folder -name "3.0-security/3.6-given-a-scenario-backup-restore-and-compress-files" -title "given a scenario backup restore and compress files"
Push-Location "3.0-security/3.6-given-a-scenario-backup-restore-and-compress-files"
  new-folder -name "Archive-and-restore-utilities" -title "Archive and restore utilities"
    new-markdown -name "Archive-and-restore-utilities/tar" -title "tar"
    new-markdown -name "Archive-and-restore-utilities/cpio" -title "cpio"
    new-markdown -name "Archive-and-restore-utilities/dd" -title "dd"
  new-folder -name "Compression" -title "Compression"
    new-markdown -name "Compression/gzip" -title "gzip"
    new-markdown -name "Compression/xz" -title "xz"
    new-markdown -name "Compression/bzip2" -title "bzip2"
    new-markdown -name "Compression/zip" -title "zip"
  new-folder -name "Backup-types" -title "Backup types"
    new-markdown -name "Backup-types/Incremental" -title "Incremental"
    new-markdown -name "Backup-types/Full" -title "Full"
    new-markdown -name "Backup-types/Snapshot-clones" -title "Snapshot clones"
    new-markdown -name "Backup-types/Differential" -title "Differential"
    new-markdown -name "Backup-types/Image" -title "Image"
  new-folder -name "Off-site-off-system-storage" -title "Off-site/off-system storage"
    new-markdown -name "Off-site-off-system-storage/SFTP" -title "SFTP"
    new-markdown -name "Off-site-off-system-storage/SCP" -title "SCP"
    new-markdown -name "Off-site-off-system-storage/rsync" -title "rsync"
  new-folder -name "Integrity-checks" -title "Integrity checks"
    new-markdown -name "Integrity-checks/MD5" -title "MD5"
    new-markdown -name "Integrity-checks/SHA" -title "SHA"
Pop-Location

new-folder -name "4.0-linux-troubleshooting-and-diagnostics/4.1-Given-a-scenario-analyze-system-properties-and-remediate-accordingly" -title "Given a scenario, analyze system properties and remediate accordingly"
Push-Location "4.0-linux-troubleshooting-and-diagnostics/4.1-Given-a-scenario-analyze-system-properties-and-remediate-accordingly"
  new-folder -name "Network-monitoring-and-configuration" -title "Network monitoring and configuration"
    new-folder -name "Network-monitoring-and-configuration/Latency"
      new-markdown -name "Network-monitoring-and-configuration/Latency/Bandwidth" -title "Bandwidth"
      new-markdown -name "Network-monitoring-and-configuration/Latency/Throughput" -title "Throughput"
    new-markdown -name "Network-monitoring-and-configuration/Routing" -title "Routing"
    new-markdown -name "Network-monitoring-and-configuration/Saturation" -title "Saturation"
    new-markdown -name "Network-monitoring-and-configuration/Packet-drop" -title "Packet drop"
    new-markdown -name "Network-monitoring-and-configuration/Timeouts" -title "Timeouts"
    new-markdown -name "Network-monitoring-and-configuration/Name-resolution" -title "Name resolution"
    new-markdown -name "Network-monitoring-and-configuration/Localhost-vs-Unix-socket" -title "Localhost vs. Unix socket"
    new-folder -name "Network-monitoring-and-configuration/Adapters" -title "Adapters"
      new-markdown -name "Network-monitoring-and-configuration/Adapters/RDMA-drivers" -title "RDMA-drivers"
    new-markdown -name "Network-monitoring-and-configuration/Interface-configurations" -title "Interface configurations"
    new-folder -name "Network-monitoring-and-configuration/Commands" -title "Commands"
      new-markdown -name "Network-monitoring-and-configuration/Commands/nmap" -title "nmap"
      new-markdown -name "Network-monitoring-and-configuration/Commands/netstat" -title "netstat"
      new-markdown -name "Network-monitoring-and-configuration/Commands/iftop" -title "iftop"
      new-markdown -name "Network-monitoring-and-configuration/Commands/route" -title "route"
      new-markdown -name "Network-monitoring-and-configuration/Commands/iperf" -title "iperf"
      new-markdown -name "Network-monitoring-and-configuration/Commands/tcpdump" -title "tcpdump"
      new-markdown -name "Network-monitoring-and-configuration/Commands/ipset" -title "ipset"
      new-folder -name "Network-monitoring-and-configuration/Commands/Wireshark" -title "Wireshark"
        new-markdown -name "Network-monitoring-and-configuration/Commands/Wireshark/tshark" -title "tshark"
      new-markdown -name "Network-monitoring-and-configuration/Commands/netcat" -title "netcat"
      new-markdown -name "Network-monitoring-and-configuration/Commands/traceroute" -title "traceroute"
      new-markdown -name "Network-monitoring-and-configuration/Commands/mtr" -title "mtr"
      new-markdown -name "Network-monitoring-and-configuration/Commands/arp" -title "arp"
      new-markdown -name "Network-monitoring-and-configuration/Commands/nslookup" -title "nslookup"
      new-markdown -name "Network-monitoring-and-configuration/Commands/dig" -title "dig"
      new-markdown -name "Network-monitoring-and-configuration/Commands/host" -title "host"
      new-markdown -name "Network-monitoring-and-configuration/Commands/whois" -title "whois"
      new-markdown -name "Network-monitoring-and-configuration/Commands/ping" -title "ping"
      new-markdown -name "Network-monitoring-and-configuration/Commands/nmcli" -title "nmcli"
      new-markdown -name "Network-monitoring-and-configuration/Commands/ip" -title "ip"
      new-markdown -name "Network-monitoring-and-configuration/Commands/tracepath" -title "tracepath"
  new-folder -name "Storage-monitoring-and-configuration" -title "Storage monitoring and configuration"
    new-markdown -name "Storage-monitoring-and-configuration/iostat" -title "iostat"
    new-markdown -name "Storage-monitoring-and-configuration/ioping" -title "ioping"
    new-folder -name "Storage-monitoring-and-configuration/IO-scheduling" -title "IO scheduling"
      new-markdown -name "Storage-monitoring-and-configuration/IO-scheduling/cfq" -title "cfq"
      new-markdown -name "Storage-monitoring-and-configuration/IO-scheduling/noop" -title "noop"
      new-markdown -name "Storage-monitoring-and-configuration/IO-scheduling/deadline" -title "deadline"
    new-markdown -name "Storage-monitoring-and-configuration/du" -title "du"
    new-markdown -name "Storage-monitoring-and-configuration/df" -title "df"
    new-markdown -name "Storage-monitoring-and-configuration/LVM-tools" -title "LVM tools"
    new-markdown -name "Storage-monitoring-and-configuration/fsck" -title "fsck"
    new-markdown -name "Storage-monitoring-and-configuration/partprobe" -title "partprobe"
  new-folder -name "CPU-monitoring-and-configuration" -title "CPU monitoring and configuration"
    new-markdown -name "CPU-monitoring-and-configuration/proc-cpuinfo" -title "/proc/cpuinfo"
    new-markdown -name "CPU-monitoring-and-configuration/uptime" -title "uptime"
    new-markdown -name "CPU-monitoring-and-configuration/loadaverage" -title "loadaverage"
    new-markdown -name "CPU-monitoring-and-configuration/sar" -title "sar"
    new-markdown -name "CPU-monitoring-and-configuration/sysctl" -title "sysctl"
  new-folder -name "Memory-monitoring-and-configuration" -title "Memory monitoring and configuration"
    new-markdown -name "Memory-monitoring-and-configuration/swapon" -title "swapon"
    new-markdown -name "Memory-monitoring-and-configuration/swapoff" -title "swapoff"
    new-markdown -name "Memory-monitoring-and-configuration/mkswap" -title "mkswap"
    new-markdown -name "Memory-monitoring-and-configuration/vmstat" -title "vmstat"
    new-markdown -name "Memory-monitoring-and-configuration/Out-of-memory-killer" -title "Out of memory killer"
    new-markdown -name "Memory-monitoring-and-configuration/free" -title "free"
    new-markdown -name "Memory-monitoring-and-configuration/proc-meminfo" -title "/proc/meminfo"
    new-markdown -name "Memory-monitoring-and-configuration/Buffer-cache-output" -title "Buffer cache output"
  new-folder -name "Lost-root-password" -title "Lost root password"
    new-markdown -name "Lost-root-password/Single-user-mode" -title "Single user mode"
Pop-Location

new-folder -name "4.0-linux-troubleshooting-and-diagnostics/4.2-given-a-scenario-analyze-system-processes-in-order-to-optimize-performance" -title "given a scenario analyze system processes in order to optimize performance"
Push-Location "4.0-linux-troubleshooting-and-diagnostics/4.2-given-a-scenario-analyze-system-processes-in-order-to-optimize-performance"
  new-folder -name "Process-management" -title "Process management"
    new-folder -name "Process-management/Process-states" -title "Process states"
      new-markdown -name "Process-management/Process-states/Zombie" -title "Zombie"
      new-markdown -name "Process-management/Process-states/Uninterruptible-sleep" -title "Uninterruptible sleep"
      new-markdown -name "Process-management/Process-states/Interruptible-sleep" -title "Interruptible sleep"
      new-markdown -name "Process-management/Process-states/Running"
    new-markdown -name "Process-management/Priorities"
    new-markdown -name "Process-management/Kill-signals" -title "kill signals"
    new-folder -name "Process-management/Commands" -title "commands"
      new-markdown -name "Process-management/Commands/nice" -title "nice"
      new-markdown -name "Process-management/Commands/renice" -title "renice"
      new-markdown -name "Process-management/Commands/top" -title "top"
      new-markdown -name "Process-management/Commands/time" -title "time"
      new-markdown -name "Process-management/Commands/ps" -title "ps"
      new-markdown -name "Process-management/Commands/lsof" -title "lsof"
      new-markdown -name "Process-management/Commands/pgrep" -title "pgrep"
      new-markdown -name "Process-management/Commands/pkill" -title "pkill"
    new-markdown -name "Process-management/PIDs" -title "PIDs"
Pop-Location

new-folder -name "4.0-linux-troubleshooting-and-diagnostics/4.3-given-a-scenario-analyze-and-troubleshoot-user-issues" -title "given a scenario analyze and troubleshoot user issues"
Push-Location "4.0-linux-troubleshooting-and-diagnostics/4.3-given-a-scenario-analyze-and-troubleshoot-user-issues"
  new-folder -name "Permissions" -title "Permissions"
    new-markdown -name "Permissions/File" -title "File"
    new-markdown -name "Permissions/Directory" -title "Directory"
  new-folder -name "Access" -title "Access"
    new-markdown -name "Access/Local" -title "Local"
    new-markdown -name "Access/Remote" -title "Remote"
  new-folder -name "Authentication" -title "Authentication"
    new-markdown -name "Authentication/Local" -title "Local"
    new-markdown -name "Authentication/External" -title "External"
    new-markdown -name "Authentication/Policy-violations" -title "Policy violations"
  new-folder -name "File-creation" -title "File creation"
    new-markdown -name "File-creation/Quotas" -title "Quotas"
    new-markdown -name "File-creation/Storage" -title "Storage"
    new-markdown -name "File-creation/Inode-exhaustion" -title "Inode exhaustion"
    new-markdown -name "File-creation/Immutable-files" -title "Immutable files"
  new-folder -name "Insufficient-privileges-for-authorization" -title "Insufficient privileges for authorization"
    new-markdown -name "Insufficient-privileges-for-authorization/SELinux-violations" -title "SELinux violations"
  new-markdown -name "Environment-and-shell-issues" -title "Environment and shell issues" 
Pop-Location

new-folder -name "4.0-linux-troubleshooting-and-diagnostics/4.4-given-a-scenario-analyze-and-troubleshoot-application-and-hardware-issues" -title "given a scenario analyze and troubleshoot application and hardware issues"
Push-Location "4.0-linux-troubleshooting-and-diagnostics/4.4-given-a-scenario-analyze-and-troubleshoot-application-and-hardware-issues"
  new-markdown -name "SELinux-context-violations" -title "SELinux context violations"
  new-folder -name "Storage" -title "Storage"
    new-markdown -name "Storage/Degraded-storage" -title "Degraded storage"
    new-markdown -name "Storage/Missing-devices" -title "Missing devices"
    new-markdown -name "Storage/Missing-volumes" -title "Missing volumes"
    new-markdown -name "Storage/Missing-mount-point" -title "Missing mount point"
    new-markdown -name "Storage/Performance-issues" -title "Performance issues"
    new-markdown -name "Storage/Resource-exhaustion" -title "Resource exhaustion"
    new-folder -name "Storage/Adapters" -title "Adapters"
      new-markdown -name "Storage/Adapters/SCSI" -title "SCSI"
      new-markdown -name "Storage/Adapters/RAID" -title "RAID"
      new-markdown -name "Storage/Adapters/SATA" -title "SATA"
      new-folder -name "Storage/Adapters/HBA" -title "HBA"
        new-markdown -name "Storage/Adapters/HBA/sys-class-scsi-host-host-scan" -title "/sys/class/scsi_host/host#/scan"
    new-folder -name "Storage/Storage-integrity" -title "Storage integrity" 
      new-markdown -name "Storage/Storage-integrity/Bad-blocks" -title "Bad blocks"
  new-folder -name "Firewall" -title "Firewall"
    new-markdown -name "Firewall/Restrictive-ACLs" -title "Restrictive ACLs"
    new-markdown -name "Firewall/Blocked-ports" -title "Blocked ports"
    new-markdown -name "Firewall/Blocked-protocols" -title "Blocked protocols"
  new-folder -name "Permission" -title "Permission"
    new-markdown -name "Permission/Ownership" -title "Ownership"
    new-markdown -name "Permission/Executables" -title "Executables"
    new-markdown -name "Permission/Inheritance" -title "Inheritance"
    new-markdown -name "Permission/Service-accounts" -title "Service accounts"
    new-markdown -name "Permission/Group-memberships" -title "Group memberships"
  new-folder -name "Dependencies" -title "Dependencies"
    new-markdown -name "Dependencies/Patching" -title "Patching"
    new-markdown -name "Dependencies/Update-issues" -title "Update issues"
    new-markdown -name "Dependencies/Versioning" -title "Versioning"
    new-markdown -name "Dependencies/Libraries" -title "Libraries"
    new-markdown -name "Dependencies/Environment-variables" -title "Environment variables"
    new-markdown -name "Dependencies/GCC-compatibility" -title "GCC compatibility"
    new-markdown -name "Dependencies/Repositories" -title "Repositories"
  new-folder -name "Troubleshooting-additional-hardware-issues" -title "Troubleshooting additional hardware issues"
    new-markdown -name "Troubleshooting-additional-hardware-issues/Memory" -title "Memory"
    new-markdown -name "Troubleshooting-additional-hardware-issues/Printers" -title "Printers"
    new-folder -name "Troubleshooting-additional-hardware-issues/Video" -title "Video"
      new-markdown -name "Troubleshooting-additional-hardware-issues/Video/GPU-drivers" -title "GPU drivers"
    new-markdown -name "Troubleshooting-additional-hardware-issues/Communications-ports" -title "Communications ports"
    new-markdown -name "Troubleshooting-additional-hardware-issues/USB" -title "USB"
    new-markdown -name "Troubleshooting-additional-hardware-issues/Keyboard-mapping" -title "Keyboard mapping"
    new-markdown -name "Troubleshooting-additional-hardware-issues/Hardware-or-software-compatibility-issues" -title "Hardware or software compatibility issues"
    new-folder -name "Troubleshooting-additional-hardware-issues/Commands" -title "Commands"
      new-markdown -name "Troubleshooting-additional-hardware-issues/Commands/dmidecode" -title "dmidecode"
      new-markdown -name "Troubleshooting-additional-hardware-issues/Commands/lshw" -title "lshw"
Pop-Location

new-folder -name "5.0-automation-and-scripting/5.1-given-a-scenario-deploy-and-execute-basic-bash-scripts" -title "given a scenario deploy and execute basic bash scripts"
Push-Location "5.0-automation-and-scripting/5.1-given-a-scenario-deploy-and-execute-basic-bash-scripts"
  new-folder -name "Shell-environments-and-shell-variables" -title "Shell environments and shell variables"
    new-markdown -name "Shell-environments-and-shell-variables/PATH" -title "PATH"
    new-markdown -name "Shell-environments-and-shell-variables/Global" -title "Global"
    new-markdown -name "Shell-environments-and-shell-variables/Local" -title "Local"
    new-markdown -name "Shell-environments-and-shell-variables/export" -title "export"
    new-markdown -name "Shell-environments-and-shell-variables/env" -title "env"
    new-markdown -name "Shell-environments-and-shell-variables/set" -title "set"
    new-markdown -name "Shell-environments-and-shell-variables/printenv" -title "printenv"
    new-markdown -name "Shell-environments-and-shell-variables/echo" -title "echo"
  new-markdown -name "bin-bash" -title "#!/bin/bash" 
  new-markdown -name "Sourcing-scripts" -title "Sourcing scripts"
  new-folder -name "Directory-and-file-permissions" -title "Directory and file permissions"
    new-markdown -name "Directory-and-file-permissions/chmod" -title "chmod"
  new-markdown -name "Extensions" -title "Extensions"  
  new-markdown -name "Commenting" -title "Commenting"
  new-markdown -name "File-globbing" -title "File globbing"
  new-markdown -name "Shell-expansions" -title "Shell expansions"
  new-markdown -name "Redirection-and-piping" -title "Redirection and piping"
  new-folder -name "Exit-codes" -title "Exit codes"
    new-markdown -name "Exit-codes/stderr" -title "stderr"
    new-markdown -name "Exit-codes/stdin" -title "stdin"
    new-markdown -name "Exit-codes/stdout" -title "stdout"
  new-markdown -name "Metacharacters" -title "Metacharacters"
  new-markdown -name "Positional-parameters" -title "Positional parameters"
  new-folder -name "Looping-constructs" -title "Looping constructs"
    new-markdown -name "Looping-constructs/while" -title "while"
    new-markdown -name "Looping-constructs/for" -title "for"
    new-markdown -name "Looping-constructs/until" -title "until"
  new-folder -name "Conditional-statements" -title "Conditional statements"
    new-markdown -name "Conditional-statements/if" -title "if"
    new-markdown -name "Conditional-statements/case" -title "case"
  new-markdown -name "Escaping-characters" -title "Escaping characters"
Pop-Location

new-folder -name "5.0-automation-and-scripting/5.2-given-a-scenario-carry-out-version-control-using-git" -title "given a scenario carry out version control using git"
Push-Location "5.0-automation-and-scripting/5.2-given-a-scenario-carry-out-version-control-using-git"
  new-folder -name "Arguments" -title "Arguments"
    new-markdown -name "Arguments/clone" -title "clone"
    new-markdown -name "Arguments/push" -title "push"
    new-markdown -name "Arguments/pull" -title "pull"
    new-markdown -name "Arguments/commit" -title "commit"
    new-markdown -name "Arguments/merge" -title "merge"
    new-markdown -name "Arguments/branch" -title "branch"
    new-markdown -name "Arguments/log" -title "log"
    new-markdown -name "Arguments/init" -title "init"
    new-markdown -name "Arguments/config" -title "config"
  new-folder -name "Files" -title "Files"
    new-markdown -name "Files/gitignore" -title ".gitignore"
    new-markdown -name "Files/git" -title ".git/"
Pop-Location

new-folder -name "5.0-automation-and-scripting/5.3-summarize-orchestration-processes-and-concepts" -title "summarize orchestration processes and concepts"
Push-Location "5.0-automation-and-scripting/5.3-summarize-orchestration-processes-and-concepts"
  new-markdown -name "Agent" -title "Agent"
  new-markdown -name "Agentless" -title "Agentless"
  new-markdown -name "Procedures" -title "Procedures"
  new-markdown -name "Attributes" -title "Attributes"
  new-markdown -name "Infrastructure-automation" -title "Infrastructure automation"
  new-markdown -name "Infrastructure-as-code" -title "Infrastructure as code"
  new-markdown -name "Inventory" -title "Inventory"
  new-markdown -name "Automated-configuration-management" -title "Automated configuration management"
  new-markdown -name "Build-automation" -title "Build automation"
Pop-Location
